language: python
cache: pip
python:
    # Check https://github.com/zrzka/blackmamba/issues/7
    # - 2.7.13
    - 3.6
install:
    - pip install -r requirements.txt
before_script:
    - flake8 . --count --max-complexity=10 --max-line-length=124 --statistics --exclude lib
script:
    - PYTHONPATH=. pytest tests
notifications:
    on_success: change
    on_failure: always
